### ISSUE TITLE
Fail to properly bundle libQt5Gui

### ISSUE THREAD

**Issue by azubieta** [TheAssassin/linuxdeploy-plugin-qt#4]
The build process goes well but I got the following error at run-time:

`bin/appimage_metadata_extractor: relocation error: /tmp/squashfs-root/usr/bin/../lib/libQt5Gui.so.5: symbol qt_version_tag version Qt_5.10 not defined in file libQt5Core.so.5 with link time reference`

Build log: https://travis-ci.org/azubieta/appimage-metadata-extractor/builds/395880498

@probonopd as you were working on linuxdeployqt, I would like to ask you if you have any clue about this error.

**Comment by probonopd** [comment]
Looks like either no or the wrong version of `libQt5Gui.so.5` got bundled.

**Comment by azubieta** [comment]
Well there was only one version of qt installed in the build system and the libs were include properly as far as I can tell. 
Here is the resulting AppImage:
https://github.com/azubieta/appimage-metadata-extractor/releases/download/continuous/AppImage_Metadata_Extractor-x86_64.AppImage

**Comment by probonopd** [comment]
Can you try bundling it with `linuxdeployqt`?

**Comment by azubieta** [comment]
Waiting for it 
https://travis-ci.org/azubieta/appimage-metadata-extractor/builds/396474441

**Comment by TheAssassin** [comment]
@probonopd the library is definitely bundled, but perhaps linuxdeploy's Qt plugin is missing some binary patching or something like that. I wrote most of its code by looking at linuxdeployqt, but linuxdeployqt is quite complex, and sometimes the code is a bit cumbersome. So I think there's that tiny bit missing that makes up linuxdeployqt's magic.

**Comment by TheAssassin** [comment]
I think I fixed it in the last commit. Please retry.

**Comment by TheAssassin** [comment]
Closing as solved. Please reopen if you're still affected by this issue.

linuxdeploy-plugin-qt works pretty well now in my opinion. Once we have QML deployment, we're pretty much ready to release it to a broader audience.

**Comment by azubieta** [comment]
Still being affected by this issue :cry: 
please check https://travis-ci.org/azubieta/appimage-metadata-extractor/builds/402723993

**Comment by TheAssassin** [comment]
The log seems right to me. Please explain your current issue.

**Comment by TheAssassin** [comment]
https://github.com/TheAssassin/AppImageLauncher/releases provides AppImages built with linuxdeploy, and I just powered up a Tumbleweed KDE Live ISO in a VM to check whether this one works. It works perfectly fine there, @azubieta. My best guess is that due to you trying to influence qmake's behavior using some environment variable, the plugin mixes system and other libraries. But I can't tell for sure. All I can say is that the plugin works fine for most projects, except yours.

**Comment by TheAssassin** [comment]
Fixed in https://github.com/TheAssassin/linuxdeploy-plugin-qt/commit/db0089036d1b488c9bdb71364fe948a4543a64fd. One of the least obvious bugs I have _ever_ encountered.

Quoting the detailed commit message:

> ### Use patchelf v0.8
> 
> Seems like 0.10 breaks Qt libraries which expect a symbol called `qt_version_tag` in a specific section in the symbols. Patchelf breaks this by apparently moving the symbols to another section (section `15` vs. `13`).
> We found out by looking into the readelf outputs of `libQt5Core.so.5`. @azubieta spotted the different numbers, and looked up their meaning.
> 
> linuxdeployqt uses the patchelf binaries Debian jessie provides, which is 0.8. Therefore we try to build that version from source instead, hoping that this version won't break libraries.
> 
> If that doesn't work either, we'll try with the pre-built binaries.

Big thanks to @azubieta who's debugged this with me tonight. I invested hours into this already. I am going to report the issue upstream, to have it fixed in the latest versions.

**Comment by azubieta** [comment]
Thanks to you for also being there :+1:
